image: node:20

pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - GITLAB_PAGES=true VITE_SHEETS_WEBHOOK_URL=$VITE_SHEETS_WEBHOOK_URL VITE_SHEETS_WEBHOOK_SECRET=$VITE_SHEETS_WEBHOOK_SECRET npm run build
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - main
